In [1]:
import numpy as np
arr=np.array([[1,2,3,4,5,6,]], np.int64)
print(arr)

[[1 2 3 4 5 6]]


In [2]:
print(arr.shape)

(1, 6)


In [3]:
print(arr.dtype)

int64


In [4]:
print(arr[0,1])

2


In [5]:
list=np.array([[1,2,3],[1,2,4],[1,2,3]])
print(list.shape)

(3, 3)


In [6]:
a=np.array({1,2,3,4})
print(a)

{1, 2, 3, 4}


In [7]:
zero= np.zeros((1,2))
print(zero)

[[0. 0.]]


In [8]:
print(zero.dtype)

float64


In [9]:
rng=np.arange(15)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [10]:
lspace=np.linspace(1,50,4)
print(lspace)

[ 1.         17.33333333 33.66666667 50.        ]


In [11]:
emp=np.empty((4,6))
print(emp)

[[1.17287459e-316 0.00000000e+000 6.91308323e-310 5.34129627e-317
  5.33943858e-317 6.91308320e-310]
 [5.33921329e-317 6.91308320e-310 5.33866389e-317 5.34035161e-317
  5.34016980e-317 5.33890894e-317]
 [6.91308320e-310 5.33941091e-317 5.33912633e-317 5.34126465e-317
  5.34123303e-317 5.34213815e-317]
 [6.91308320e-310 6.91308320e-310 6.91308320e-310 6.91308320e-310
  5.33844254e-317 6.91307796e-310]]


In [12]:
emp_like=np.empty_like(lspace)
print(emp_like)

[ 1.         17.33333333 33.66666667 50.        ]


In [13]:
IDE=np.identity(45)
print(IDE)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [14]:
print(IDE.shape)

(45, 45)


In [15]:
arr=np.arange(99)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [16]:
arr=(arr.reshape(3,33))

In [17]:
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]


In [18]:
print(arr.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


numpy axis

In [19]:
arr3=np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13],[14,15,16,17]])
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]
 [14 15 16 17]]


In [20]:
print("axis=0",arr3.sum(axis=0))
print("axis=1",arr3.sum(axis=1))

axis=0 [30 34 38 42]
axis=1 [10 26 46 62]


In [21]:
print(arr3.T)

[[ 1  5 10 14]
 [ 2  6 11 15]
 [ 3  7 12 16]
 [ 4  8 13 17]]


In [22]:
print(arr3.ndim)

2


In [23]:
for item in arr3.flat:
    print(item)

1
2
3
4
5
6
7
8
10
11
12
13
14
15
16
17


In [24]:
print(arr3.size)

16


In [25]:
print(arr3.nbytes)

128


In [26]:
one=np.array([1,2,3,4,5])

In [27]:
print(one.argmax())  #max element index

4


In [28]:
print(one.argmin()) #minimum element index

0


In [29]:
print(arr3.argsort())

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [30]:
print(arr3.argmin())

0


In [31]:
print(arr3.argmax())

15


In [32]:
print(arr3.argmax(axis=0))

[3 3 3 3]


In [33]:
arr3=np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13],[14,15,16,17]])

print(arr3.argmax(axis=1))

[3 3 3 3]


In [34]:
print(arr3.argsort(axis=1))

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [35]:
print(arr3.ravel())
print(arr3.reshape(axis=0))

[ 1  2  3  4  5  6  7  8 10 11 12 13 14 15 16 17]


TypeError: 'axis' is an invalid keyword argument for this function

In [ ]:
a=[12,4,5,6]
b=[1,2,4,5]
print(a+b)

[12, 4, 5, 6, 1, 2, 4, 5]


In [ ]:
a=np.array(a)
b=np.array(b)
print(a*b)
print(a.sum(),b.sum())

[12  8 20 30]
27 12


In [ ]:
print(np.where(a>5))

(array([0, 3]),)


In [ ]:
print(type(np.where(a>5)))

<class 'tuple'>


In [ ]:
print(np.count_nonzero(a))
a=[12,4,5,6]
print(a[1,2])

4


In [ ]:
print(np.nonzero(arr3))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


In [ ]:
ch=[0,6,4,7]
npa=np.array(ch)