In [27]:
import numpy as np

# Creating a NumPy array
a = np.array([1, 2, 3, 4, 5])

# Computing the sum of array elements
print(np.sum(a))  # Output: 15

# Finding the maximum value in the array
print(np.max(a))  # Output: 5

# Finding the minimum value in the array
print(np.min(a))  # Output: 1

# Finding the number of elements in the array
print(np.size(a))  # Output: 5

# Calculating the mean (average) of array elements
print(np.mean(a))  # Output: 3.0

# Computing the cumulative sum of array elements
print(np.cumsum(a))  # Output: [ 1  3  6 10 15]

# Computing the cumulative product of array elements
print(np.cumprod(a))  # Output: [  1   2   6  24 120]

# Creating two arrays for price and quantity
price = np.array([100, 200, 45, 45, 43, 354])
quantity = np.array([1, 3, 4, 5, 6, 7])

# Displaying price and quantity arrays
print(price, "\n", quantity)

# Calculating cumulative product along axis 0 (row-wise)
c = np.cumprod([quantity, price], axis=0)
print(c)
# Output:
# [[  1   3   4   5   6   7]
#  [100 300 1200 6000 36000 252000]]

# Summing the second row of the cumulative product
print(c[1].sum())  # Output: 299900


15
5
1
5
3.0
[ 1  3  6 10 15]
[  1   2   6  24 120]
[100 200  45  45  43 354] 
 [1 3 4 5 6 7]
[[   1    3    4    5    6    7]
 [ 100  600  180  225  258 2478]]
3841


In [ ]:
# Question:
# Consider an initial array arr with elements [2, 3, 4, 5, 6]. Perform the following operations:

# Calculate the cumulative product of the array.



In [ ]:
# Find the index of the element in the cumulative product array where the product exceeds 100.

In [ ]:

# Display the resulting cumulative product array and the index found in step 2.

In [ ]:
# Write Python code to implement these operations and display the results.