In [1]:
import numpy as np

# Array Creation
array1 = np.array([1, 2, 3])
array_zeros = np.zeros((2, 3))
array_ones = np.ones((3, 2))
array_range = np.arange(0, 10, 2)
array_linspace = np.linspace(0, 1, 5)

# Print and Explanation
print("Array Creation:")
print("array1:", array1)  # 1D array
print("array_zeros:")
print(array_zeros)  # 2D array of zeros
print("array_ones:")
print(array_ones)   # 2D array of ones
print("array_range:", array_range)  # 1D array with values from 0 to 10 (exclusive) with step 2
print("array_linspace:", array_linspace)  # 1D array with 5 evenly spaced values between 0 and 1


Array Creation:
array1: [1 2 3]
array_zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
array_ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
array_range: [0 2 4 6 8]
array_linspace: [0.   0.25 0.5  0.75 1.  ]


In [8]:
# Array Operations
array2 = np.array([4, 5, 6])
array_addition = array1 + array2
array_dot_product = np.dot(array1, array2)
array_transpose = np.transpose(array_zeros)
array_sum = np.sum(array1)
array_mean = np.mean(array2)
array_max = np.max(array1)
array_min = np.min(array2)

# Print and Explanation
print("\nArray Operations:")
print("array_addition:", array_addition)  # Element-wise addition
print("array_dot_product:", array_dot_product)  # Dot product of arrays
print("array_transpose:")
print(array_transpose)  # Transpose of array_zeros
print("array_sum:", array_sum)  # Sum of array1
print("array_mean:", array_mean)  # Mean of array2
print("array_max:", array_max)  # Maximum value in array1
print("array_min:", array_min)  # Minimum value in array2



Array Operations:
array_addition: [5 7 9]
array_dot_product: 32
array_transpose:
[[0. 0.]
 [0. 0.]
 [0. 0.]]
array_sum: 6
array_mean: 5.0
array_max: 3
array_min: 4


In [10]:
# Array Manipulation
array3 = np.array([[7, 8, 9], [10, 11, 12]])
array_reshape = np.reshape(array_range, (1, 5))  # Corrected shape to (1, 5) or (5, 1)
array_concatenate = np.concatenate((array1, array2))
array_vstack = np.vstack((array1, array2))
array_hstack = np.hstack((array_zeros, array3))

# Print and Explanation
print("\nArray Manipulation:")
print("array_reshape:")
print(array_reshape)  # Reshape array_range to a 1x5 matrix
print("array_concatenate:", array_concatenate)  # Concatenate arrays
print("array_vstack:")
print(array_vstack)  # Vertically stack arrays
print("array_hstack:")
print(array_hstack)  # Horizontally stack arrays



Array Manipulation:
array_reshape:
[[0 2 4 6 8]]
array_concatenate: [1 2 3 4 5 6]
array_vstack:
[[1 2 3]
 [4 5 6]]
array_hstack:
[[ 0.  0.  0.  7.  8.  9.]
 [ 0.  0.  0. 10. 11. 12.]]


In [1]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.delete(a,0,axis=1))

[[1 2 3 4]
 [5 6 7 8]]
[[2 3 4]
 [6 7 8]]
