In [31]:
import numpy as np

# Sorting a 2D array row-wise
a = np.array([[2, 4, 3, 5, 6, 1, 9, 8], [2, 4, 3, 5, 6, 1, 9, 8]])
print(np.sort(a))  # Sort each row in ascending order


[[1 2 3 4 5 6 8 9]
 [1 2 3 4 5 6 8 9]]


In [30]:
# Filtering even numbers from an array
a = np.array([12, 13, 14, 15])
fa = a % 2 == 0
ne = a[fa]
print(ne)  # Output: [12, 14]

[12 14]


In [29]:
# Searching for elements divisible by 5 and getting their indices
ar = np.array([4, 5, 67, 5, 2, 23, 55, 4])
s = np.where(ar % 5 == 0)
print(s)  # Output: (array([1, 3, 6]),)

(array([1, 3, 6]),)


In [27]:
# Binary search to find the index where 4 would be inserted to maintain sorted order
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.searchsorted(a, 4)
print(b)  # Output: 3


3


In [32]:
# Filtering an array based on a boolean array
a = np.array([12, 13, 14, 15])
fa = [True, False, True, False]
new = a[fa]
print(new)  # Output: [12, 14]

[12 14]
